import {
  defineProperties,
  createSprinkles,
} from "@vanilla-extract/sprinkles";
import { vars } from "./tokens.css";
import { contentWidths } from "./layout";

const space = {
  none: 0,
  px: 1,
  "0.5": 2,
  "1": 4,
  "1.5": 6,
  "2": 8,
  "2.5": 10,
  "3": 12,
  "3.5": 14,
  "4": 16,
  "5": 20,
  "6": 24,
  "7": 28,
  "8": 32,
  "10": 40,
  "12": 48,
  "14": 56,
  "16": 64,
  "20": 80,
} as const;

const radii = {
  none: 0,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  "2xl": 24,
  "3xl": 30,
  full: 9999,
} as const;

const layoutProps = defineProperties({
  conditions: {
    base: {},
    md: { "@media": "screen and (min-width: 768px)" },
    lg: { "@media": "screen and (min-width: 1024px)" },
  },
  defaultCondition: "base",
  properties: {
    display: [
      "none",
      "block",
      "inline",
      "inline-block",
      "flex",
      "inline-flex",
      "grid",
      "inline-grid",
    ],
    flexDirection: ["row", "column", "row-reverse", "column-reverse"],
    flexWrap: ["wrap", "nowrap", "wrap-reverse"],
    alignItems: [
      "stretch",
      "flex-start",
      "center",
      "flex-end",
      "baseline",
    ],
    justifyContent: [
      "flex-start",
      "center",
      "flex-end",
      "space-between",
      "space-around",
      "space-evenly",
    ],
    flex: ["1 1 0%", "1 1 auto", "0 1 auto", "none"],
    gap: space,
    rowGap: space,
    columnGap: space,
    padding: space,
    paddingTop: space,
    paddingRight: space,
    paddingBottom: space,
    paddingLeft: space,
    paddingInline: space,
    paddingBlock: space,
    margin: space,
    marginTop: space,
    marginRight: space,
    marginBottom: space,
    marginLeft: space,
    marginInline: space,
    marginBlock: space,
    width: ["auto", "100%", "fit-content", "max-content", "min-content"],
    height: ["auto", "100%", "fit-content"],
    minWidth: { "0": 0, full: "100%" },
    minHeight: { "0": 0, full: "100%" },
    maxWidth: { full: "100%", screen: "100vw", ...contentWidths },
    borderRadius: radii,
    borderTopLeftRadius: radii,
    borderTopRightRadius: radii,
    borderBottomLeftRadius: radii,
    borderBottomRightRadius: radii,
    position: ["static", "relative", "absolute", "fixed", "sticky"],
    overflow: ["visible", "hidden", "auto", "scroll"],
    overflowX: ["visible", "hidden", "auto", "scroll"],
    overflowY: ["visible", "hidden", "auto", "scroll"],
    textAlign: ["left", "center", "right"],
    cursor: ["pointer", "default", "not-allowed", "text"],
    pointerEvents: ["auto", "none"],
    zIndex: { auto: "auto", "0": 0, "1": 1, "2": 2, "10": 10, "20": 20 },
  },
  shorthands: {
    p: ["padding"],
    pt: ["paddingTop"],
    pr: ["paddingRight"],
    pb: ["paddingBottom"],
    pl: ["paddingLeft"],
    px: ["paddingInline"],
    py: ["paddingBlock"],
    m: ["margin"],
    mt: ["marginTop"],
    mr: ["marginRight"],
    mb: ["marginBottom"],
    ml: ["marginLeft"],
    mx: ["marginInline"],
    my: ["marginBlock"],
    w: ["width"],
    h: ["height"],
    rounded: ["borderRadius"],
  },
});

const colorProps = defineProperties({
  properties: {
    color: {
      ink: vars.ink,
      inkSoft: vars.inkSoft,
      muted: vars.muted,
      paper: vars.paper,
      bezel: vars.bezel,
      textOnAccent: vars.textOnAccent,
      accent: vars.accent.primary,
      now: vars.accent.now,
      done: vars.accent.done,
      secondary: vars.accent.secondary,
      success: vars.status.success,
      warning: vars.status.warning,
      error: vars.status.error,
      info: vars.status.info,
      blue: vars.swatches.blue,
      green: vars.swatches.green,
      violet: vars.swatches.violet,
      indigo: vars.swatches.indigo,
      cyan: vars.swatches.cyan,
      amber: vars.swatches.amber,
      rose: vars.swatches.rose,
      teal: vars.swatches.teal,
      inherit: "inherit",
    },
    background: {
      transparent: "transparent",
      paper: vars.paper,
      ink: vars.ink,
      bezel: vars.bezel,
      overlay: vars.overlay,
      glassBg: vars.glass.bg,
      glassBgDeep: vars.glass.bgDeep,
      glassBgSoft: vars.glass.bgSoft,
      accent: vars.accent.primary,
      now: vars.accent.now,
      done: vars.accent.done,
      success: vars.status.success,
      warning: vars.status.warning,
      error: vars.status.error,
      info: vars.status.info,
      blue: vars.swatches.blue,
      green: vars.swatches.green,
      violet: vars.swatches.violet,
      indigo: vars.swatches.indigo,
      cyan: vars.swatches.cyan,
      amber: vars.swatches.amber,
      rose: vars.swatches.rose,
      teal: vars.swatches.teal,
    },
    borderColor: {
      rule: vars.rule,
      stroke: vars.glass.stroke,
      ink: vars.ink,
      bezel: vars.bezel,
      accent: vars.accent.primary,
      success: vars.status.success,
      warning: vars.status.warning,
      error: vars.status.error,
      info: vars.status.info,
      transparent: "transparent",
    },
  },
  shorthands: {
    bg: ["background"],
  },
});

export const sprinkles = createSprinkles(layoutProps, colorProps);
export type Sprinkles = Parameters<typeof sprinkles>[0];
