import {
  defineProperties,
  createSprinkles,
} from "@vanilla-extract/sprinkles";
import { vars } from "./tokens.css";
import {
  space,
  radii,
  contentWidth,
  borderWidth,
  zIndex,
  media,
} from "./scales";

const layoutProps = defineProperties({
  conditions: {
    base: {},
    md: { "@media": media.tabletUp },
    lg: { "@media": media.desktopUp },
  },
  defaultCondition: "base",
  properties: {
    display: [
      "none",
      "block",
      "inline",
      "inline-block",
      "flex",
      "inline-flex",
      "grid",
      "inline-grid",
    ],
    flexDirection: ["row", "column", "row-reverse", "column-reverse"],
    flexWrap: ["wrap", "nowrap", "wrap-reverse"],
    alignItems: [
      "stretch",
      "flex-start",
      "center",
      "flex-end",
      "baseline",
    ],
    justifyContent: [
      "flex-start",
      "center",
      "flex-end",
      "space-between",
      "space-around",
      "space-evenly",
    ],
    flex: ["1 1 0%", "1 1 auto", "0 1 auto", "none"],
    gap: space,
    rowGap: space,
    columnGap: space,
    padding: space,
    paddingTop: space,
    paddingRight: space,
    paddingBottom: space,
    paddingLeft: space,
    paddingInline: space,
    paddingBlock: space,
    margin: space,
    marginTop: space,
    marginRight: space,
    marginBottom: space,
    marginLeft: space,
    marginInline: space,
    marginBlock: space,
    width: ["auto", "100%", "fit-content", "max-content", "min-content"],
    height: ["auto", "100%", "fit-content"],
    minWidth: { "0": 0, full: "100%" },
    minHeight: { "0": 0, full: "100%" },
    maxWidth: { ...contentWidth, full: "100%", screen: "100vw" },
    borderRadius: radii,
    borderTopLeftRadius: radii,
    borderTopRightRadius: radii,
    borderBottomLeftRadius: radii,
    borderBottomRightRadius: radii,
    borderWidth: borderWidth,
    borderTopWidth: borderWidth,
    borderRightWidth: borderWidth,
    borderBottomWidth: borderWidth,
    borderLeftWidth: borderWidth,
    borderStyle: ["solid", "dashed", "dotted", "none"],
    position: ["static", "relative", "absolute", "fixed", "sticky"],
    overflow: ["visible", "hidden", "auto", "scroll"],
    overflowX: ["visible", "hidden", "auto", "scroll"],
    overflowY: ["visible", "hidden", "auto", "scroll"],
    textAlign: ["left", "center", "right"],
    cursor: ["pointer", "default", "not-allowed", "text"],
    pointerEvents: ["auto", "none"],
    zIndex: { auto: "auto", ...zIndex },
  },
  shorthands: {
    p: ["padding"],
    pt: ["paddingTop"],
    pr: ["paddingRight"],
    pb: ["paddingBottom"],
    pl: ["paddingLeft"],
    px: ["paddingInline"],
    py: ["paddingBlock"],
    m: ["margin"],
    mt: ["marginTop"],
    mr: ["marginRight"],
    mb: ["marginBottom"],
    ml: ["marginLeft"],
    mx: ["marginInline"],
    my: ["marginBlock"],
    w: ["width"],
    h: ["height"],
    rounded: ["borderRadius"],
  },
});

const colorProps = defineProperties({
  properties: {
    color: {
      ink: vars.ink,
      inkSoft: vars.inkSoft,
      muted: vars.muted,
      paper: vars.paper,
      bezel: vars.bezel,
      textOnAccent: vars.textOnAccent,
      accent: vars.accent.primary,
      now: vars.accent.now,
      done: vars.accent.done,
      secondary: vars.accent.secondary,
      success: vars.status.success,
      warning: vars.status.warning,
      error: vars.status.error,
      info: vars.status.info,
      blue: vars.swatches.blue,
      green: vars.swatches.green,
      violet: vars.swatches.violet,
      indigo: vars.swatches.indigo,
      cyan: vars.swatches.cyan,
      amber: vars.swatches.amber,
      rose: vars.swatches.rose,
      teal: vars.swatches.teal,
      inherit: "inherit",
    },
    background: {
      transparent: "transparent",
      paper: vars.paper,
      ink: vars.ink,
      bezel: vars.bezel,
      overlay: vars.overlay,
      glassBg: vars.glass.bg,
      glassBgDeep: vars.glass.bgDeep,
      glassBgSoft: vars.glass.bgSoft,
      hoverFill: vars.interactive.hoverFill,
      selectedFill: vars.interactive.selectedFill,
      accent: vars.accent.primary,
      now: vars.accent.now,
      done: vars.accent.done,
      success: vars.status.success,
      warning: vars.status.warning,
      error: vars.status.error,
      info: vars.status.info,
      blue: vars.swatches.blue,
      green: vars.swatches.green,
      violet: vars.swatches.violet,
      indigo: vars.swatches.indigo,
      cyan: vars.swatches.cyan,
      amber: vars.swatches.amber,
      rose: vars.swatches.rose,
      teal: vars.swatches.teal,
    },
    borderColor: {
      rule: vars.rule,
      stroke: vars.glass.stroke,
      ink: vars.ink,
      bezel: vars.bezel,
      accent: vars.accent.primary,
      success: vars.status.success,
      warning: vars.status.warning,
      error: vars.status.error,
      info: vars.status.info,
      transparent: "transparent",
    },
  },
  shorthands: {
    bg: ["background"],
  },
});

export const sprinkles = createSprinkles(layoutProps, colorProps);
export type Sprinkles = Parameters<typeof sprinkles>[0];
