export { AppShell } from "./AppShell";
export { Sidebar } from "./Sidebar";
export { MobileTabs } from "./MobileTabs";
export { CapturePalette } from "./CapturePalette";
export { CaptureProvider, useCapture } from "./CaptureContext";
export { AssistantProvider, useAssistant } from "./AssistantContext";
export type { AssistantScope } from "./AssistantContext";
export { SearchPalette } from "./SearchPalette";
export { SearchProvider, useSearch } from "./SearchContext";
export { NAV_ITEMS, MOBILE_TABS } from "./nav";
export type { NavItem } from "./nav";
