/**
 * EngineMessage models
 *
 * Structured, discriminated messages the engine emits to describe scheduling
 * failures and warnings. The renderer maps these into console-friendly
 * {tag, title, body} tuples; a future action layer will map them into
 * proposed actions ("push deadline", "raise priority", "edit blocker Y").
 *
 * Persistence model: rows are engine-derived. On each regen the engine emits
 * a fresh array while consulting the previous array to carry forward the
 * user-owned `dismissed` flag. The diff sync applies creates/updates/deletes
 * against the deterministic id.
 *
 * Identity model: the id captures both "same recurring source" (so the
 * engine emits one row per unique instance rather than spamming the console
 * with 400 recurring-travel duplicates) and "same specific instance" (so
 * dismissal survives regens as long as the id matches). Per type the id
 * fields are:
 *   - INSUFFICIENT_TRAVEL: from | to | actualMinutes | timeOfDay | dayOfWeek
 *   - SCHEDULED_LATE:      plannerId | scheduledStart
 *   - TASK_TOO_LARGE:      plannerId
 *   - TASK_UNSCHEDULABLE:  plannerId | reason
 *   - SCHEDULED_OK:        placedCount
 *
 * Any change to a discriminating field (placement shift, new reason, new
 * travel numbers, new placed count) produces a new id → surfaces as a new
 * row.
 *
 * Naming note: the DB-shaped row type is `EngineMessage` in @/types/prisma
 * (payload widened to `JsonValue`, plus userId/createdAt/updatedAt).
 * The engine-internal, narrow-payload emit shape is `EngineMessageEmit` here
 * — kept as a distinct name so a mis-import can't quietly downgrade a
 * discriminated payload into a JsonValue at a distant call site.
 */

import type { SchedulingFailureReason } from "../constants";

export type EngineMessageTone = "fail" | "warn" | "info";

export type EngineMessageType =
  | "TASK_TOO_LARGE"
  | "TASK_UNSCHEDULABLE"
  | "SCHEDULED_LATE"
  | "INSUFFICIENT_TRAVEL"
  | "SCHEDULED_OK";

/**
 * Type-specific structured payloads. Every payload references its subject
 * entities by id so a rename doesn't rot the message; presentation strings
 * are derived at render time from the current entity tree.
 */
export type EngineMessagePayload =
  | {
      type: "TASK_TOO_LARGE";
      plannerId: string;
      duration: number;
      maxCapacity: number;
    }
  | {
      // Prose is generated by the renderer from `reason` — the engine emits
      // structured facts only. Keeping presentation strings out of JSONB
      // means a reason-copy rewrite doesn't require a data migration.
      type: "TASK_UNSCHEDULABLE";
      plannerId: string;
      reason: SchedulingFailureReason;
    }
  | {
      type: "SCHEDULED_LATE";
      plannerId: string;
      deadline: string;
      scheduledStart: string;
      daysLate: number;
    }
  | {
      type: "INSUFFICIENT_TRAVEL";
      fromLocationId: string | null;
      toLocationId: string | null;
      actualMinutes: number;
      requiredMinutes: number;
      shortageMinutes: number;
      dayOfWeek: number;
      timeOfDay: string;
      affectedCount: number;
    }
  | {
      // Informational summary emitted once per regen when at least one
      // planner event landed. Id includes the count so a change in
      // placement count naturally supersedes the prior row and the user
      // sees an updated card (a dismissed "12 placed" doesn't hide a fresh
      // "14 placed").
      type: "SCHEDULED_OK";
      placedCount: number;
    };

/**
 * Engine-emitted message shape (pre-persistence). `id` is deterministic
 * (see identity model above) and `dismissed` is carried forward from the
 * previous regen's array — the engine never flips it from true to false on
 * its own; only the user's dismiss action does.
 */
export type EngineMessageEmit = {
  id: string;
  type: EngineMessageType;
  tone: EngineMessageTone;
  payload: EngineMessagePayload;
  dismissed: boolean;
};

/**
 * Delimiter between message type and body fields in the deterministic id.
 * Chosen so it can't appear in a planner uuid, a location id, or an ISO
 * timestamp, and so a body that itself joins sub-fields with a plain "|"
 * can't collide with the outer separator. Change requires a migration that
 * rewrites existing row ids.
 */
export const MESSAGE_ID_DELIM = "::";

/**
 * Placeholder for null components inside a joined body. Deliberately does
 * NOT contain the outer delimiter so future code that splits an id by
 * MESSAGE_ID_DELIM won't mis-parse a null part.
 */
export const NULL_ID_SENTINEL = "__null__";

function idPart(value: string | number | null | undefined): string {
  if (value === null || value === undefined) return NULL_ID_SENTINEL;
  return String(value);
}

function joinBody(...parts: (string | number | null | undefined)[]): string {
  return parts.map(idPart).join("|");
}

export function taskTooLargeId(plannerId: string): string {
  return `TASK_TOO_LARGE${MESSAGE_ID_DELIM}${idPart(plannerId)}`;
}

export function taskUnschedulableId(
  plannerId: string,
  reason: SchedulingFailureReason,
): string {
  return `TASK_UNSCHEDULABLE${MESSAGE_ID_DELIM}${joinBody(plannerId, reason)}`;
}

export function scheduledLateId(
  plannerId: string,
  scheduledStart: string,
): string {
  return `SCHEDULED_LATE${MESSAGE_ID_DELIM}${joinBody(plannerId, scheduledStart)}`;
}

/**
 * INSUFFICIENT_TRAVEL id — five discriminating fields. Repeat instances of
 * the same recurring leg (same route, same weekday, same time-of-day, same
 * actual minutes) share this id and fold to one row inside the engine;
 * anything shifted produces a new id and surfaces as a new row.
 */
export function insufficientTravelId(fields: {
  fromLocationId: string | null;
  toLocationId: string | null;
  actualMinutes: number;
  timeOfDay: string;
  dayOfWeek: number;
}): string {
  return `INSUFFICIENT_TRAVEL${MESSAGE_ID_DELIM}${joinBody(
    fields.fromLocationId,
    fields.toLocationId,
    fields.actualMinutes,
    fields.timeOfDay,
    fields.dayOfWeek,
  )}`;
}

export function scheduledOkId(placedCount: number): string {
  return `SCHEDULED_OK${MESSAGE_ID_DELIM}${idPart(placedCount)}`;
}
