/**
 * EngineMessage models
 *
 * Structured, discriminated messages the engine emits to describe scheduling
 * failures and warnings. The renderer maps these into console-friendly
 * {tag, title, body} tuples; a future action layer will map them into
 * proposed actions ("push deadline", "raise priority", "edit blocker Y").
 *
 * Persistence model: rows are engine-derived. On each regen the engine emits
 * a fresh array while consulting the previous array to carry forward the
 * user-owned `dismissed` flag. The diff sync applies creates/updates/deletes
 * against the deterministic id.
 *
 * Identity model: the id captures both "same recurring source" (so the
 * engine emits one row per unique instance rather than spamming the console
 * with 400 recurring-travel duplicates) and "same specific instance" (so
 * dismissal survives regens as long as the id matches). Per type the id
 * fields are:
 *   - INSUFFICIENT_TRAVEL: from | to | actualMinutes | timeOfDay | dayOfWeek
 *   - SCHEDULED_LATE:      plannerId | scheduledStart
 *   - TASK_TOO_LARGE:      plannerId
 *   - TASK_UNSCHEDULABLE:  plannerId | reason
 *   - SPLIT_CONSTRAINT_RELAXED: plannerId | kind | affectedCount | totalMinutes
 *   - GOAL_DAY_CAP_RELAXED: plannerId | kind | affectedCount | totalMinutes
 *   - QUEUE_SEQUENCE_BROKEN: queueId | failedPlannerId
 *   - DEPENDENCY_BROKEN:   predecessorId | successorId | cause
 *   - SEQUENCE_PAST_HORIZON: predecessorId | successorId
 *   - SCHEDULED_OK:        placedCount
 *
 * Any change to a discriminating field (placement shift, new reason, new
 * travel numbers, new placed count) produces a new id → surfaces as a new
 * row.
 *
 * Naming note: the DB-shaped row type is `EngineMessage` in @/types/prisma
 * (payload widened to `JsonValue`, plus userId/createdAt/updatedAt).
 * The engine-internal, narrow-payload emit shape is `EngineMessageEmit` here
 * — kept as a distinct name so a mis-import can't quietly downgrade a
 * discriminated payload into a JsonValue at a distant call site.
 */

import type { SchedulingFailureReason } from "../constants";

export type EngineMessageTone = "fail" | "warn" | "info";

export type EngineMessageType =
  | "TASK_TOO_LARGE"
  | "TASK_UNSCHEDULABLE"
  | "SCHEDULED_LATE"
  | "INSUFFICIENT_TRAVEL"
  | "SPLIT_CONSTRAINT_RELAXED"
  | "GOAL_DAY_CAP_RELAXED"
  | "QUEUE_SEQUENCE_BROKEN"
  | "DEPENDENCY_BROKEN"
  | "SEQUENCE_PAST_HORIZON"
  | "SCHEDULED_OK";

/**
 * Type-specific structured payloads. Every payload references its subject
 * entities by id so a rename doesn't rot the message; presentation strings
 * are derived at render time from the current entity tree.
 */
export type EngineMessagePayload =
  | {
      type: "TASK_TOO_LARGE";
      plannerId: string;
      duration: number;
      maxCapacity: number;
    }
  | {
      // Prose is generated by the renderer from `reason` — the engine emits
      // structured facts only. Keeping presentation strings out of JSONB
      // means a reason-copy rewrite doesn't require a data migration.
      type: "TASK_UNSCHEDULABLE";
      plannerId: string;
      reason: SchedulingFailureReason;
      // Split tasks only: a partial placement failed with these minutes
      // still unplaced (the placed chunks stay on the calendar). Absent for
      // plain tasks and total failures.
      remainingMinutes?: number;
      placedMinutes?: number;
    }
  | {
      type: "SCHEDULED_LATE";
      plannerId: string;
      deadline: string;
      scheduledStart: string;
      daysLate: number;
    }
  | {
      type: "INSUFFICIENT_TRAVEL";
      fromLocationId: string | null;
      toLocationId: string | null;
      actualMinutes: number;
      requiredMinutes: number;
      shortageMinutes: number;
      dayOfWeek: number;
      timeOfDay: string;
      affectedCount: number;
    }
  | {
      // A split task's constraints were compromised to place its minutes:
      // "maxChunk" = a remainder below twice the minimum chunk can only
      // place whole and exceeded the max chunk size; "dayCap" = the final
      // pass placed chunks past the per-day cap rather than dropping them.
      // One row per (plannerId, kind); count/minutes in the id so a change
      // supersedes the prior row.
      type: "SPLIT_CONSTRAINT_RELAXED";
      plannerId: string;
      kind: "maxChunk" | "dayCap";
      affectedCount: number;
      totalMinutes: number;
    }
  | {
      // A goal's daily cap was exceeded to place its subtree: "oversizedLeaf"
      // = a single block (or a split leaf's minimum chunk) is bigger than the
      // cap and placed whole; "dayCap" = the final pass placed minutes past
      // the cap rather than dropping them. One row per (plannerId, kind);
      // capMinutes is an emit-time fact and stays out of the id.
      type: "GOAL_DAY_CAP_RELAXED";
      plannerId: string;
      kind: "oversizedLeaf" | "dayCap";
      affectedCount: number;
      totalMinutes: number;
      capMinutes: number;
    }
  | {
      // A queue member permanently failed to place, so later members were
      // scheduled without waiting for it. One row per (queueId,
      // failedPlannerId) — every successor bound to the same failed member
      // folds into the one card. Both fields ride in the id.
      type: "QUEUE_SEQUENCE_BROKEN";
      queueId: string;
      failedPlannerId: string;
    }
  | {
      // A dependency predecessor failed ("failed") or is an unready goal
      // ("unready") — the successor was scheduled without waiting for it.
      // A prerequisite never stops being a prerequisite, so the unready
      // case is loud here where the queue equivalent skips silently.
      type: "DEPENDENCY_BROKEN";
      predecessorId: string;
      successorId: string;
      cause: "failed" | "unready";
    }
  | {
      // Budget-exhaustion flavor for both sources: the predecessor's only
      // failure is that its forecast extends past the scheduling horizon —
      // the sequence didn't break, the calendar just can't see that far.
      type: "SEQUENCE_PAST_HORIZON";
      source: "queue" | "dependency";
      queueId: string | null;
      predecessorId: string;
      successorId: string;
    }
  | {
      // Informational summary emitted once per regen when at least one
      // planner event landed. Id includes the count so a change in
      // placement count naturally supersedes the prior row and the user
      // sees an updated card (a dismissed "12 placed" doesn't hide a fresh
      // "14 placed").
      type: "SCHEDULED_OK";
      placedCount: number;
    };

/**
 * Engine-emitted message shape (pre-persistence). `id` is deterministic
 * (see identity model above) and `dismissed` is carried forward from the
 * previous regen's array — the engine never flips it from true to false on
 * its own; only the user's dismiss action does.
 */
export type EngineMessageEmit = {
  id: string;
  type: EngineMessageType;
  tone: EngineMessageTone;
  payload: EngineMessagePayload;
  dismissed: boolean;
};

/**
 * Delimiter between message type and body fields in the deterministic id.
 * Chosen so it can't appear in a planner uuid, a location id, or an ISO
 * timestamp, and so a body that itself joins sub-fields with a plain "|"
 * can't collide with the outer separator. Change requires a migration that
 * rewrites existing row ids.
 */
export const MESSAGE_ID_DELIM = "::";

/**
 * Placeholder for null components inside a joined body. Deliberately does
 * NOT contain the outer delimiter so future code that splits an id by
 * MESSAGE_ID_DELIM won't mis-parse a null part.
 */
export const NULL_ID_SENTINEL = "__null__";

function idPart(value: string | number | null | undefined): string {
  if (value === null || value === undefined) return NULL_ID_SENTINEL;
  return String(value);
}

function joinBody(...parts: (string | number | null | undefined)[]): string {
  return parts.map(idPart).join("|");
}

export function taskTooLargeId(plannerId: string): string {
  return `TASK_TOO_LARGE${MESSAGE_ID_DELIM}${idPart(plannerId)}`;
}

export function taskUnschedulableId(
  plannerId: string,
  reason: SchedulingFailureReason,
): string {
  return `TASK_UNSCHEDULABLE${MESSAGE_ID_DELIM}${joinBody(plannerId, reason)}`;
}

export function scheduledLateId(
  plannerId: string,
  scheduledStart: string,
): string {
  return `SCHEDULED_LATE${MESSAGE_ID_DELIM}${joinBody(plannerId, scheduledStart)}`;
}

/**
 * INSUFFICIENT_TRAVEL id — five discriminating fields. Repeat instances of
 * the same recurring leg (same route, same weekday, same time-of-day, same
 * actual minutes) share this id and fold to one row inside the engine;
 * anything shifted produces a new id and surfaces as a new row.
 */
export function insufficientTravelId(fields: {
  fromLocationId: string | null;
  toLocationId: string | null;
  actualMinutes: number;
  timeOfDay: string;
  dayOfWeek: number;
}): string {
  return `INSUFFICIENT_TRAVEL${MESSAGE_ID_DELIM}${joinBody(
    fields.fromLocationId,
    fields.toLocationId,
    fields.actualMinutes,
    fields.timeOfDay,
    fields.dayOfWeek,
  )}`;
}

export function splitConstraintRelaxedId(fields: {
  plannerId: string;
  kind: "maxChunk" | "dayCap";
  affectedCount: number;
  totalMinutes: number;
}): string {
  return `SPLIT_CONSTRAINT_RELAXED${MESSAGE_ID_DELIM}${joinBody(
    fields.plannerId,
    fields.kind,
    fields.affectedCount,
    fields.totalMinutes,
  )}`;
}

export function goalDayCapRelaxedId(fields: {
  plannerId: string;
  kind: "oversizedLeaf" | "dayCap";
  affectedCount: number;
  totalMinutes: number;
}): string {
  return `GOAL_DAY_CAP_RELAXED${MESSAGE_ID_DELIM}${joinBody(
    fields.plannerId,
    fields.kind,
    fields.affectedCount,
    fields.totalMinutes,
  )}`;
}

export function queueSequenceBrokenId(
  queueId: string,
  failedPlannerId: string,
): string {
  return `QUEUE_SEQUENCE_BROKEN${MESSAGE_ID_DELIM}${joinBody(queueId, failedPlannerId)}`;
}

export function dependencyBrokenId(
  predecessorId: string,
  successorId: string,
  cause: "failed" | "unready",
): string {
  return `DEPENDENCY_BROKEN${MESSAGE_ID_DELIM}${joinBody(predecessorId, successorId, cause)}`;
}

export function sequencePastHorizonId(
  predecessorId: string,
  successorId: string,
): string {
  return `SEQUENCE_PAST_HORIZON${MESSAGE_ID_DELIM}${joinBody(predecessorId, successorId)}`;
}

export function scheduledOkId(placedCount: number): string {
  return `SCHEDULED_OK${MESSAGE_ID_DELIM}${idPart(placedCount)}`;
}
